### ISSUE TITLE
[ISSUE] DynamicPlaylist creation fails if an excluded genre contains a single quote	

### ISSUE THREAD

**Issue by TaurusI76** [AF-1/lms-dynamicplaylists#14]
## Checklist

❗️ **Please take a quick look at [**this checklist**](https://github.com/AF-1/sobras/wiki/Checklist-to-eliminate-common-causes-of-LMS-(plugin)-problems) to eliminate common causes of LMS (plugin) problems. Thank you.**
<br><br><br>

---

## DESCRIBE THE BUG
If you add a genre containing a single quote (e.g. Children's) to the list of genres to exclude (Excluded genres) in the DynamicPlaylist plugin's settings, the dynamic playlist fails to play due to a non-escaped single quote in the playlist's SQL statement.

<br><br>
## TO REPRODUCE
1. Add a song to the library that has a genre containing a single quote.
2. Rescan library
3. In the DynamicPlaylist plugin's settings, add the genre to the Excluded Genres list.
4. Play a dynamic playlist (e.g. Songs - never played (APC))
5. Playlist won't play. Instead, the main dynamic playlist selection screen is shown.

<br><br>
## EXPECTED BEHAVIOR
The dynamic playlist will be added to the playlist and will play.

<br><br>
## LOG EXCERPT
2024/02/29 08:53:57,stdout,"[24-02-29 08:53:57.6244] Slim::Schema::Storage::throw_exception (121) Error: DBI Exception: DBD::SQLite::db prepare failed: near \"s\": syntax error [for Statement \"select tracks.id, tracks.primary_artist from tracks left join library_track on library_track.track = tracks.id join alternativeplaycount on alternativeplaycount.urlmd5 = tracks.urlmd5 and ifnull(alternativeplaycount.playCount, 0) = 0 left join dynamicplaylist_history on dynamicplaylist_history.id = tracks.id and dynamicplaylist_history.client = '10:7b:44:93:2e:02' where tracks.audio = 1 and dynamicplaylist_history.id is null and tracks.secs >= 90 and not exists (select * from tracks t2,genre_track,genres where t2.id = tracks.id and tracks.id = genre_track.track and genre_track.genre = genres.id and genres.name in ('Non-Music','Children's','Comedy','Books & Spoken','Audiobook','Hörspiel')) and case when ('' != '' and '' is not null) then library_track.library = '' else 1 end group by tracks.id\"]
"

<br><br>
## NAME/CODE OF DYNAMIC PLAYLIST
Songs - never played (APC)

<br><br>
## VERSION INFO
* LMS version: 8.4.1
* OS (version): Synology DSM 7.2.1-69057 Update 3
* Plugin version: v4.3.5
* Web skin/controller: LMS Default
* Browser (version): Google Chrome Version 122.0.6261.70

**Comment by AF-1** [comment]
Thanks for letting me know. I don't have genres with single quotes so it never came up.
Should be fixed in 4.3.6.

**Comment by TaurusI76** [comment]
Thanks! I thought it's probably easier for you to fix it than for me to dig
through the code & contribute.
Thank you for fixing it!
