### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by legolas136** [AF-1/lms-dynamicplaylists#16]
I don't know, if this is the right spot to ask for features. Sorry, if wrong.

When creating dynamic playlists, I miss the option to filter for "Comment is not empty" I can only filter for "contains, contains not, starts with and starts not with".

Greetings

**Comment by AF-1** [comment]
I'm guessing this is about the _Dynamic Playlist Creator_ plugin and the _Random Tracks - Advanced_ template. The next DPLC release will have a comments search option "has a value". That should do what you want.

**Comment by legolas136** [comment]
Yes, exactly. Thank you for your support!
